CREATE DATABASE IF NOT EXISTS cpftunand;
CREATE DATABASE IF NOT EXISTS rest_061222;
CREATE DATABASE IF NOT EXISTS sia_fti_20121;
CREATE DATABASE IF NOT EXISTS portal_24012008;

GRANT ALL PRIVILEGES ON cpftunand.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON rest_061222.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON sia_fti_20121.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON portal_24012008.* TO 'user'@'%';

FLUSH PRIVILEGES;
